### ISSUE TITLE
MyHarmony App does not discover hue-upnp

### ISSUE THREAD

**Issue by troych** [falk0069/hue-upnp#7]
Hi there, I'm trying to get this to run rather unsuccessfully. Tried on my openwrt router (where it should run ideally) and on my htpc running ubuntu. Same result with both, the myharmony app isn't able to discover hue-upnp.

There is nothing in the log suggesting any  communication between the two. I can access description.xml on the webserver so I know it's serving content, not sure where stuff goes wrong.

Any pointers or more info I can provide?

Harmony Hub (and Ultimate One) Firmware: 4.8.25
hue-upnp config: http://pastebin.com/raw/R7F6sLB7
hue-upnp log: http://pastebin.com/raw/MWCr3hLH

**Comment by falk0069** [comment]
At initial glance it would appear that the python script is running in a different vlan than your harmony.  Do you know the IP address of your harmony?  Does it start with: 192.168.22.xxx?  I've never seen such a quiet log before.  Normally there is all sorts if upnp chatter it picks up.

**Comment by troych** [comment]
Yep, IP of my harmony hub is 192.168.22.177, I'll double check in the MyHarmony config but I'm pretty sure it's correctly setup since I see it on the active wireless devices with this IP on the router. Sadly I don't seem to be able to manually assign it an IP/Subnet to make sure everything is setup correctly.

**Comment by troych** [comment]
Sorry for the double post, but on my HTPC I get upnp chatter now and the pairing goes through. Sadly this is not the case on my router, but at least I've got a working config and can start from there to see where exactly things fail.

**Comment by jimboca** [comment]
Is the hue-upnp running on a WiFi device? I've heard other hub emulators
had issues with that setup.

**Comment by troych** [comment]
Yup, it's running on a router with openwrt. (Does have 2.4/5GHZ wlan) Don't have any other device that is always on. :/ 

I'll keep trying and update if I suddenly get it working.

**Comment by jimboca** [comment]
Ya, sorry I see that now that I reread your original post. Maybe the router
doesn't let all upnp traffic thru to other processes since most routers
respond to upnp for other stuff?

**Comment by troych** [comment]
I had it working shortly but then the Internet wasn't working anymore, certainly has something to do with the router seeming to block upnp packets in certain conditions. Investigating further... Thanks for the nudge in the correct direction. :)

**Comment by troych** [comment]
Got it working on my second router that is usually just running as a bridge. Now it's the hue bridge. :D Still not entirely sure why it wouldn't work on my main one, I guess it could be a similar problem this dude had: https://forum.openwrt.org/viewtopic.php?id=43160

Anyway, could now sync to hue-upnp, now I just need to get WOL working but I think that is the easy bit. Thanks again for the pointers.
